name: Publish

on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    name: Publish release
    env:
      HEX_API_KEY: ${{secrets.HEX_API_KEY}}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.0
          rebar3-version: 3.24
      - run: rebar3 hex publish -r hexpm --yes